### ISSUE TITLE
Customize rocket stack size

### ISSUE THREAD

**Issue by Marabus69** [Stargateur/ArtilleryShellStack#1]
It would be really helpful if you added the ability to customize the rocket stack size of the shells aswell as its really annoying only being able to fit 10 of them on one rocket

**Comment by Stargateur** [comment]
Closes by https://github.com/Stargateur/ArtilleryShellStack/commit/c3f515e6a0c3c4d4a45ed1f27ff304edbff9de5c

Thx for the idea
